#!/usr/bin/bash

#SBATCH -A b1081
#SBATCH -p b1081
#SBATCH -t 100:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH -J fmriprep_changedatatype
# Outputs ----------------------------------
#SBATCH --mail-user=dianaperez@u.northwestern.edu
#SBATCH --mail-type=ALL
# ------------------------------------------

# SUBJECT (make an input eventually)
subject="LS03"

# set up some directory information
BIDS_DIR="/projects/b1081/Lifespan"
DERIVS_DIR="derivatives/preproc_fmriprep-20.2.0"
WORK_DIR="/projects/b1081/singularity_images/work_dp"

# convert BOLD volume files to float
module load fsl
for filename in ${BIDS_DIR}/${DERIVS_DIR}/fmriprep/sub-${subject}/ses-*/func/sub-${subject}_*_desc-preproc_bold.nii.gz
do
  fslmaths -dt input ${filename} ${filename} -odt float
done
