#!/usr/bin/bash

#SBATCH -A p31161
#SBATCH -p long
#SBATCH -t 168:00:00
#SBATCH --mem=0
#SBATCH -J fmriprep_lifespan_LS07
# Outputs ----------------------------------
#SBATCH --mail-user=dianaperez@u.northwestern.edu
#SBATCH --mail-type=ALL
# ------------------------------------------

# SUBJECT (make an input eventually)
subject="LS07"

# set up some directory information
BIDS_DIR="/projects/p31161/Lifespan" #points to data
DERIVS_DIR="/projects/b1081/Lifespan/derivatives" #points to output dir
WORK_DIR="/projects/b1081/singularity_images/work_dp2" #points to work dir

# Prepare derivatives folder and work dirs
mkdir -p ${DERIVS_DIR}/preproc_fmriprep-20.0.6 
mkdir -p ${WORK_DIR}

# Load modules
module purge
module load singularity
echo "modules loaded" 

# To reuse freesurfer directories
mkdir -p ${DERIVS_DIR}/freesurfer-6.0.1
if [ ! -d ${DERIVS_DIR}/preproc_fmriprep-20.0.6/freesurfer ]; then
    ln -s ${DERIVS_DIR}/freesurfer-6.0.1 ${DERIVS_DIR}/preproc_fmriprep-20.0.6/freesurfer
fi

# remove IsRunning files from Freesurfer
find ${DERIVS_DIR}/freesurfer-6.0.1/sub-$subject/ -name "*IsRunning*" -type f -delete

# do singularity run
echo "Begin Preprocessing"

singularity run --cleanenv -B /projects/p31161,/projects/b1081:/projects/b1081 \
    /projects/b1081/singularity_images/fmriprep-20.0.6.simg \
    ${BIDS_DIR} \
    ${DERIVS_DIR}/preproc_fmriprep-20.0.6 \
    participant --participant-label ${subject} \
    -w ${WORK_DIR} --omp-nthreads 8 --nthreads 12 --mem_mb 3000 \
    --fs-license-file /projects/b1081/singularity_images/freesurfer_license.txt \
    --fs-subjects-dir ${DERIVS_DIR}/freesurfer-6.0.1 \
    --output-spaces MNI152NLin6Asym:res-2 \
    --ignore slicetiming --fd-spike-threshold 0.2
